name: Docker CI

on:
  push:
    branches: [ main ]  # Trigger only on pushes to `main` branch
    tags: [ 'v*' ]      # Optional: Trigger on version tags (e.g., v1.0.0)

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Required for pushing to Docker Hub

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to latest version

      - name: Log in to Docker Hub
        uses: docker/login-action@v3  # Updated to latest version
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5  # Updated to latest version
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/your-repo-name:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/your-repo-name:${{ github.sha }}
